### ISSUE TITLE
ERROR: odrive 0.4.4.dev0 requires pywin32>=222, which is not installed

### ISSUE THREAD

**Issue by john-bessire** [neomanic/odrive_ros#13]
I was attempting to install odrive_ros on an Nvidia TX1 board using Ubuntu 16.04 but the error message is for a missing pywin32 Windows module.  Does odrive_ros run on Linux or is there some other installation procedure I should use?

    git clone https://github.com/neomanic/ODrive -b py27compat
    cd ODrive/tools
    sudo pip install monotonic # required for py < 3

    # sudo python setup.py install # doesn't work due to weird setup process, so do the following:
    python setup.py sdist
    sudo pip install dist/odrive-0.4.4.dev0.tar.gz

  Building wheel for odrive (setup.py) ... done
  Created wheel for odrive: filename=odrive-0.4.4.dev0-cp27-none-any.whl size=52586 sha256=7322ab60660491c87a061f4b9daa979071be46c8a6bcb0aeb531454086652da8
  Stored in directory: /home/nvidia/.cache/pip/wheels/26/82/3e/3ce48c01b59c09d3e1fae82c86f4d659e14b89f4235b5b8ae5
Successfully built odrivehttps://github.com/neomanic/odrive_ros/issues/new
**_ERROR: odrive 0.4.4.dev0 requires pywin32>=222, which is not installed._**
Installing collected packages: odrive
  Found existing installation: odrive 0.4.4.dev0
    Uninstalling odrive-0.4.4.dev0:
      Successfully uninstalled odrive-0.4.4.dev0
Successfully installed odrive-0.4.4.dev0

**Comment by neomanic** [comment]
Yes, definitely works under Ubuntu 16.04 and Kinetic. Did you follow the instructions in the lower bit? I have that 

```python setup.py sdist
sudo pip install dist/odrive-0.4.4.dev0.tar.gz
```

bit precisely because the regular install fails due to the pywin32 requirement.

Also, install the mainline ODrive tools and ignore that bit at the top about installing the py27compat branch. I've fixed this readme in the next update which I'll push through next week (currently behind a firewall which makes it a pain.)

**Comment by john-bessire** [comment]
We finally got it working after installing the ODrive tools.

EDIT:  After trying to install on other systems we found out the versions of iPython and PIP were causing problems.  Uninstall PIP and then install version 9.

    sudo pip install --upgrade pip==9.0.1
