### ISSUE TITLE
Why the i2t_update_rate is 0.01?

### ISSUE THREAD

**Issue by milano-technical-intern** [neomanic/odrive_ros#14]
Hi,

I don't know if it's an error or I'm missing something but, why the i2t_update_rate is set to be 0.01? I was expecting to be 0.1 because that's the rate of the fast_timer.

Best,

**Comment by neomanic** [comment]
It's just unfortunately poorly named, it's not how often the i2t is updated but rather a weighting that determines how quickly the current through the motor affects the temperature. So it will be proportional to the thermal mass and will vary motor-to-motor.

(ps sorry for the slow reply... I was away for a month from work)
