### ISSUE TITLE
Does this provide an /odom topic? Also will this work with mecanum wheels? 

### ISSUE THREAD

**Issue by GrushBrush** [neomanic/odrive_ros#21]
Hi, does this provide odometry topic like odom? 

Also I'm thinking about these omni wheels, are they compatible with Odrive and this ros package? 

https://www.aliexpress.com/item/4000271714727.html?spm=a2g0s.8937460.0.0.816c2e0eOTO4V9
Thanks for your hard work.

**Comment by neomanic** [comment]
Hi Grush, sorry for not checking on the issues here for a long time. I've just added an archive notice since I no longer have access to testing.

To answer your questions:
- yes it provides an odom topic
- no, those wheels look like they are brushed DC, and therefore don't need a brushless driver
