### ISSUE TITLE
Correct measurremnt for tyre_circumference parameter?

### ISSUE THREAD

**Issue by luckydaemon** [neomanic/odrive_ros#23]
I'm using odrive for controlling robot, based on hover board wheels. Wheels diameter is 6.5 inches, so I thought that i need to set parameter "tyre_circumference" in launch file to 0.51 (meters). But when I am sendin to cmd_vel topic command with linear x = 1 (move forward with velocity 1 m/s) actual velocity send to odrive is much greater. From what I get, this is happening due to conversion  
`left_linear_val  = int((forward - angular_to_linear) * self.m_s_to_value)`
`right_linear_val = int((forward + angular_to_linear) * self.m_s_to_value)`
specifically variable  `self.m_s_to_value` which is calculated as `m_s_to_value = self.encoder_cpr/self.tyre_circumference`
In my case tyre_circumference = 0.51, and cpr set to 90 (as recommended in odrive hover board tutorial). If set tyre_circumference in centimeters, velocity converts more accurate, but still, it does not convert correctly . I can change variable  `self.m_s_to_value` to constant 1, but this can result in wrong odometry reading (? I am not actually sure about this).
So, what should I do in order to send correct velocity values (cmd_vel.linear.x = 1 -> input_vel = 1), and don't mess up odometry readings?

**Comment by Gilocho** [comment]
> 
Hello, were you able to solve this problem? I found the same thing and according to what I investigated to convert to rps (what the odrive use) the formula should be m_s_to_value =1/(2*pi*r). I'm just about to try it, although I would like to know if you found a solution to this and  the odometry is not wrong.
