### ISSUE TITLE
odrive install fails: problem with ipython

### ISSUE THREAD

**Issue by tomsepe** [neomanic/odrive_ros#8]
I am following the directions listed on the README:

> 
`git clone https://github.com/neomanic/ODrive -b py27compat`
```
cd ODrive/tools
sudo pip install monotonic
```

#sudo python setup.py install # doesn't work due to weird setup process, so do the following:
```
python setup.py sdist
sudo pip install dist/odrive-0.4.2.dev0.tar.g
```
> 

First the monotonic install fails so I added the -H flag to sudo to correct.
However the odrive install still fails becasue the version number is incorrect.
So I changed to:

`sudo -H pip install dist/odrive-0.4.4.dev0.tar.gz`

installation fails with the following message:

> 
thomas@dell-laptop:~/mw_robot/catkin_ws/src/ODrive/tools$ sudo -H pip install dist/odrive-0.4.4.dev0.tar.gz
Processing ./dist/odrive-0.4.4.dev0.tar.gz
Collecting ipython (from odrive===0.4.4.dev0)
  Downloading https://files.pythonhosted.org/packages/75/74/9b0ef91c8e356c907bb12297000951acb804583b54eeaddc342c5bad4d96/ipython-7.5.0.tar.gz (5.1MB)
    100% |████████████████████████████████| 5.1MB 267kB/s 
    Complete output from command python setup.py egg_info:
    
    IPython 7.0+ supports Python 3.5 and above.
    When using Python 2.7, please install IPython 5.x LTS Long Term Support version.
    Python 3.3 and 3.4 were supported up to IPython 6.x.
    
    See IPython `README.rst` file for more information:
    
        https://github.com/ipython/ipython/blob/master/README.rst
    
    Python sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0) detected.
    Your pip version is out of date, please install pip >= 9.0.1. pip 8.1.1 detected.

> 

I tried:
`pip install IPython==5.0 --user`

but the installation of odrive still failed with the same message.

**Comment by tomsepe** [comment]
SOLVED!

I upgraded pip:

`sudo pip install --upgrade pip==9.0.1 `

and the install worked

**Comment by neomanic** [comment]
Great. I really do need to update the readme. You don't need my fork of the main ODrive firmware+tools anymore, since the Python 2.7 compatibility has been merged back into the main dev tree.
