### ISSUE TITLE
AttributeError running odsetup() 

### ISSUE THREAD

**Issue by tomsepe** [neomanic/odrive_ros#9]
I'm following the instructions for testing with just a python shell:

> Fire up a Python shell. See below for the import which exposes the ODrive with setup and drive functions. You can use either ODriveInterfaceAPI (uses USB) or ODriveInterfaceSerial (requires the /dev/ttyUSBx corresponding to the ODrive as parameter, but not tested recently).

```
from odrive_ros import odrive_interface
od = odrive_interface.ODriveInterfaceAPI()
od.connect()
od.setup()          # does a calibration
od.engage()         # get ready to drive
od.drive(1000,1000) # drive axis0 and axis1
od.release()        # done
```

> 

I can connect to the Odrive but I get the following error:

```
>>> od.setup()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ODriveInterfaceAPI' object has no attribute 'setup'

```
>>> 

I also noticed that when I ran the odrive ROS example the motor did not calibrate.

I also noticed this error when running the odconnect() command:

`{"name":"enter_dfu_mode","id":332,"type":"function","inputs":[],"outputs":[]}]
JSON checksum: 0x8B 0xDA
malformed member : unsupported codec json
Connected to ODrive. Hardware v3.6-24, firmware v0.4.8
True
`

Don't know if it is related?

Any help appreciated!

**Comment by neomanic** [comment]
Sorry, I hadn't updated the readme to reflect changes on how you run this.
Now you don't need to call `setup()`, rather it's `od.calibrate()` after the connect, and then you can do the engage and drive.

Not sure about the json error. I'm still running an older firmware with support for preroll, so that might be why.

**Comment by neomanic** [comment]
Fixed in https://github.com/neomanic/odrive_ros/pull/17
